
ingresses:
  rules:
  - host: foo.com
    http:
      paths:
      - backend:
          service:
            name: svc1
            port:
              number: 8080
        path: /bar
        pathType: ImplementationSpecific
        # pathType: Exact
        # pathType: Prefix
