
ingresses:
  - rules:
    - host: foo.com
      http:
        paths:
        - backend:
            service:
              name: 127.0.0.1 
              port:
                number: 8099
          path: "/"
          # pathType: ImplementationSpecific
          # pathType: Exact
          # pathType: Prefix
